package me.zero.jarpwner.allatori;

import me.zero.jarpwner.allatori.transformer.AllatoriExpiryTransformer;
import me.zero.jarpwner.allatori.transformer.AllatoriWatermarkTransformer;
import me.zero.jarpwner.plugin.IPlugin;
import me.zero.jarpwner.transform.ITransformerProvider;

import java.util.Arrays;
import java.util.List;

/**
 * @author Brady
 * @since 4/1/2019
 */
public final class AllatoriPlugin implements IPlugin {

    private List<ITransformerProvider> transformers;

    @Override
    public String getName() {
        return "Allatori";
    }

    @Override
    public String getId() {
        return "allatori";
    }

    @Override
    public String getDescription() {
        return "Used to deobfuscate security measures generated by Allatori";
    }

    @Override
    public List<ITransformerProvider> getTransformers() {
        // Lazily create the transformer providers
        if (this.transformers == null) {
            this.transformers = Arrays.asList(
                    ITransformerProvider.create(AllatoriWatermarkTransformer.class, AllatoriWatermarkTransformer::new),
                    ITransformerProvider.create(AllatoriExpiryTransformer.class, AllatoriExpiryTransformer::new)
            );
        }

        return this.transformers;
    }
}
